# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8616105003f9abe6645243e25b19f95c22b68f16c75151ca5c7e28a8dfb08481b75309c89a43d942cd7f4836a03de5880d582c8cb145a09df5300e407af5c78

test:
  secret_key_base: e9a99c5c371ee4e013c6676484a43fb6f4c6cf2eebd3068a94eef0a091ffaf9297ae807d1ae5093d3aa636c48ec12f0b46cf5a5dc058db6cc092cc771ecbfb15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
